pub mod benchmark;
pub mod brill_tagger;
pub mod conllu_parser;
pub mod contextual_ruleset;
pub mod contextual_rulespec;
pub mod contractions;
pub mod lex_rulespec_id;
pub mod lexical_ruleset;
pub mod lexical_rulespec;
pub mod rulespec_id;
pub mod wordclass;
mod init_tagger;